; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.39"

; Modules
projects[ctools][version] = "1.9"

projects[colorbox][version] = "2.8"

projects[devel][version] = "1.5"

projects[entity][version] = "1.6"

projects[google_analytics][version] = "2.1"

projects[imagemagick][version] = "1.0"

projects[jquery_update][version] = "3.0-alpha2"

projects[libraries][version] = "2.2"

projects[link][version] = "1.3"

projects[oembed][version] = "0.1-beta3"

projects[pathauto][version] = "1.2"

projects[rules][version] = "2.9"

projects[themekey][version] = "3.4"

projects[token][version] = "1.6"

projects[views][version] = "3.11"

; Themes
projects[bootstrap][version] = "3.0"

projects[entity_iframe_theme][version] = "1.0"

; Modules
projects[islandora_scholar][type] = "module"
projects[islandora_scholar][download][type] = "git"
projects[islandora_scholar][download][url] = "https://github.com/Islandora/islandora_scholar"
projects[islandora_scholar][download][branch] = "7.x"
projects[islandora_scholar][download][revision] = "c564cc99723bf6129eddda3168626b349e51bd3e"

projects[islandora][type] = "module"
projects[islandora][download][type] = "git"
projects[islandora][download][url] = "https://github.com/Islandora/islandora"
projects[islandora][download][branch] = "7.x"
projects[islandora][download][revision] = "3de5b8608f3631d09a251289a6bf0bfff15ec6b5"

projects[islandora_solution_pack_audio][type] = "module"
projects[islandora_solution_pack_audio][download][type] = "git"
projects[islandora_solution_pack_audio][download][url] = "https://github.com/Islandora/islandora_solution_pack_audio"
projects[islandora_solution_pack_audio][download][branch] = "7.x"
projects[islandora_solution_pack_audio][download][revision] = "30b1000ac307132f9dfb99ddb3fc1f88fcfdac41"

projects[islandora_bagit][type] = "module"
projects[islandora_bagit][download][type] = "git"
projects[islandora_bagit][download][url] = "https://github.com/Islandora/islandora_bagit"
projects[islandora_bagit][download][branch] = "7.x"
projects[islandora_bagit][download][revision] = "b4da91dd322b15268f0b8dcef3c0d0f9ce31d457"

projects[islandora_solution_pack_collection][type] = "module"
projects[islandora_solution_pack_collection][download][type] = "git"
projects[islandora_solution_pack_collection][download][url] = "https://github.com/Islandora/islandora_solution_pack_collection"
projects[islandora_solution_pack_collection][download][branch] = "7.x"
projects[islandora_solution_pack_collection][download][revision] = "ed0cc5860d4a416be53692d325014ef65e35af0c"

projects[islandora_solution_pack_image][type] = "module"
projects[islandora_solution_pack_image][download][type] = "git"
projects[islandora_solution_pack_image][download][url] = "https://github.com/Islandora/islandora_solution_pack_image"
projects[islandora_solution_pack_image][download][branch] = "7.x"
projects[islandora_solution_pack_image][download][revision] = "a33048f36d5f1325204b85de904ffcb7c44fcba2"

projects[islandora_batch][type] = "module"
projects[islandora_batch][download][type] = "git"
projects[islandora_batch][download][url] = "https://github.com/Islandora/islandora_batch"
projects[islandora_batch][download][branch] = "7.x"
projects[islandora_batch][download][revision] = "5f0a32e5f761d29904aa375fd39240fc495b663c"

projects[islandora_solution_pack_book][type] = "module"
projects[islandora_solution_pack_book][download][type] = "git"
projects[islandora_solution_pack_book][download][url] = "https://github.com/Islandora/islandora_solution_pack_book"
projects[islandora_solution_pack_book][download][branch] = "7.x"
projects[islandora_solution_pack_book][download][revision] = "8499fd786d85daeafbbf7d2f3b0d5208135f815d"

projects[islandora_book_batch][type] = "module"
projects[islandora_book_batch][download][type] = "git"
projects[islandora_book_batch][download][url] = "https://github.com/Islandora/islandora_book_batch"
projects[islandora_book_batch][download][branch] = "7.x"
projects[islandora_book_batch][download][revision] = "1adbfcb99bb24005d8d42e0610e08aa796c1fbdc"

projects[islandora_bookmark][type] = "module"
projects[islandora_bookmark][download][type] = "git"
projects[islandora_bookmark][download][url] = "https://github.com/Islandora/islandora_bookmark"
projects[islandora_bookmark][download][branch] = "7.x"
projects[islandora_bookmark][download][revision] = "fdcf9feb5990af59471645ad341cf401e41d6acb"

projects[islandora_checksum][type] = "module"
projects[islandora_checksum][download][type] = "git"
projects[islandora_checksum][download][url] = "https://github.com/Islandora/islandora_checksum"
projects[islandora_checksum][download][branch] = "7.x"
projects[islandora_checksum][download][revision] = "c89868f41e78006db83c3cb230624f01224f03be"

projects[islandora_checksum_checker][type] = "module"
projects[islandora_checksum_checker][download][type] = "git"
projects[islandora_checksum_checker][download][url] = "https://github.com/Islandora/islandora_checksum_checker"
projects[islandora_checksum_checker][download][branch] = "7.x"
projects[islandora_checksum_checker][download][revision] = "0d1c233b1f31939b69bfea5850bfef9ec3d59ec8"

projects[islandora_solution_pack_compound][type] = "module"
projects[islandora_solution_pack_compound][download][type] = "git"
projects[islandora_solution_pack_compound][download][url] = "https://github.com/Islandora/islandora_solution_pack_compound"
projects[islandora_solution_pack_compound][download][branch] = "7.x"
projects[islandora_solution_pack_compound][download][revision] = "fa828a8713a80e545dc32cd5d26469c41a29cf0c"

projects[islandora_solution_pack_disk_image][type] = "module"
projects[islandora_solution_pack_disk_image][download][type] = "git"
projects[islandora_solution_pack_disk_image][download][url] = "https://github.com/Islandora/islandora_solution_pack_disk_image"
projects[islandora_solution_pack_disk_image][download][branch] = "7.x"
projects[islandora_solution_pack_disk_image][download][revision] = "e28d098220c260bf7585d08079de14ee4d28790a"

projects[islandora_embed][type] = "module"
projects[islandora_embed][download][type] = "git"
projects[islandora_embed][download][url] = "git@github.com:OULibraries/islandora_embed.git"
projects[islandora_embed][download][branch] = "pathauto-fix"
projects[islandora_embed][download][revision] = "a22da6aa4d987f0ffc309cbe8bc867257e75a7ed"

projects[islandora_solution_pack_entities][type] = "module"
projects[islandora_solution_pack_entities][download][type] = "git"
projects[islandora_solution_pack_entities][download][url] = "https://github.com/Islandora/islandora_solution_pack_entities"
projects[islandora_solution_pack_entities][download][branch] = "7.x"
projects[islandora_solution_pack_entities][download][revision] = "ba0ce48009883726010c0ec409d8f43937614025"

projects[islandora_fits][type] = "module"
projects[islandora_fits][download][type] = "git"
projects[islandora_fits][download][url] = "https://github.com/Islandora/islandora_fits"
projects[islandora_fits][download][branch] = "7.x"
projects[islandora_fits][download][revision] = "5e4c3d6abbd9b3c81d18a41f62eea4b875c403ca"

projects[islandora_image_annotation][type] = "module"
projects[islandora_image_annotation][download][type] = "git"
projects[islandora_image_annotation][download][url] = "https://github.com/Islandora/islandora_image_annotation"
projects[islandora_image_annotation][download][branch] = "7.x"
projects[islandora_image_annotation][download][revision] = "e32af7c356cd3f82b25b334a9d17be272b70c9ad"

projects[islandora_importer][type] = "module"
projects[islandora_importer][download][type] = "git"
projects[islandora_importer][download][url] = "https://github.com/Islandora/islandora_importer"
projects[islandora_importer][download][branch] = "7.x"
projects[islandora_importer][download][revision] = "56f82c1dccc5e3f0078fb276eabb048033dde8f5"

projects[islandora_internet_archive_bookreader][type] = "module"
projects[islandora_internet_archive_bookreader][download][type] = "git"
projects[islandora_internet_archive_bookreader][download][url] = "git@github.com:OULibraries/islandora_internet_archive_bookreader_temp.git"
projects[islandora_internet_archive_bookreader][download][branch] = "7.x-oulib-deployed"
projects[islandora_internet_archive_bookreader][download][revision] = "2838c83ee6415284e8bc39fd31d81fd62fce754d"

projects[islandora_jwplayer][type] = "module"
projects[islandora_jwplayer][download][type] = "git"
projects[islandora_jwplayer][download][url] = "https://github.com/Islandora/islandora_jwplayer"
projects[islandora_jwplayer][download][branch] = "7.x"
projects[islandora_jwplayer][download][revision] = "d5a9565c5eca1d0b3ced08feb214deff8efe99d1"

projects[islandora_solution_pack_large_image][type] = "module"
projects[islandora_solution_pack_large_image][download][type] = "git"
projects[islandora_solution_pack_large_image][download][url] = "https://github.com/Islandora/islandora_solution_pack_large_image"
projects[islandora_solution_pack_large_image][download][branch] = "7.x"
projects[islandora_solution_pack_large_image][download][revision] = "b2f0aadb20fba578fd37da1e4f9c09b03a6f0298"

projects[islandora_marcxml][type] = "module"
projects[islandora_marcxml][download][type] = "git"
projects[islandora_marcxml][download][url] = "https://github.com/Islandora/islandora_marcxml"
projects[islandora_marcxml][download][branch] = "7.x"
projects[islandora_marcxml][download][revision] = "858c94f492a4a6868fbace9b35b877b11a174069"

projects[islandora_solution_pack_newspaper][type] = "module"
projects[islandora_solution_pack_newspaper][download][type] = "git"
projects[islandora_solution_pack_newspaper][download][url] = "https://github.com/Islandora/islandora_solution_pack_newspaper"
projects[islandora_solution_pack_newspaper][download][branch] = "7.x"
projects[islandora_solution_pack_newspaper][download][revision] = "51a676c0c57e91e97fdfa5062e795265b12c6162"

projects[islandora_oai][type] = "module"
projects[islandora_oai][download][type] = "git"
projects[islandora_oai][download][url] = "https://github.com/Islandora/islandora_oai"
projects[islandora_oai][download][branch] = "7.x"
projects[islandora_oai][download][revision] = "ab021bf16a719dd5f37d477f64044028ff02071c"

projects[islandora_ocr][type] = "module"
projects[islandora_ocr][download][type] = "git"
projects[islandora_ocr][download][url] = "https://github.com/Islandora/islandora_ocr"
projects[islandora_ocr][download][branch] = "7.x"
projects[islandora_ocr][download][revision] = "453b8c89e0dadd03f4f4487d6c3c719e4a62a620"

projects[islandora_openseadragon][type] = "module"
projects[islandora_openseadragon][download][type] = "git"
projects[islandora_openseadragon][download][url] = "https://github.com/Islandora/islandora_openseadragon"
projects[islandora_openseadragon][download][branch] = "7.x"
projects[islandora_openseadragon][download][revision] = "082f895f2e0395b5544e10c75d7f50d917746777"

projects[islandora_paged_content][type] = "module"
projects[islandora_paged_content][download][type] = "git"
projects[islandora_paged_content][download][url] = "https://github.com/Islandora/islandora_paged_content"
projects[islandora_paged_content][download][branch] = "7.x"
projects[islandora_paged_content][download][revision] = "8b5eff756aeec962e9512624ac3dc7774a16f362"

projects[islandora_pathauto][type] = "module"
projects[islandora_pathauto][download][type] = "git"
projects[islandora_pathauto][download][url] = "https://github.com/Islandora/islandora_pathauto"
projects[islandora_pathauto][download][branch] = "7.x"
projects[islandora_pathauto][download][revision] = "9719695e666fd4932bbf9ce6974eb147bfcef525"

projects[islandora_solution_pack_pdf][type] = "module"
projects[islandora_solution_pack_pdf][download][type] = "git"
projects[islandora_solution_pack_pdf][download][url] = "https://github.com/Islandora/islandora_solution_pack_pdf"
projects[islandora_solution_pack_pdf][download][branch] = "7.x"
projects[islandora_solution_pack_pdf][download][revision] = "1d9f6bf77dd58e5b10771a8d3f692fc9453fafa8"

projects[islandora_pdfjs][type] = "module"
projects[islandora_pdfjs][download][type] = "git"
projects[islandora_pdfjs][download][url] = "https://github.com/Islandora/islandora_pdfjs"
projects[islandora_pdfjs][download][branch] = "7.x"
projects[islandora_pdfjs][download][revision] = "2884dc41c89232f370d1f9796b7150fe97cd5563"

projects[islandora_premis][type] = "module"
projects[islandora_premis][download][type] = "git"
projects[islandora_premis][download][url] = "https://github.com/Islandora/islandora_premis"
projects[islandora_premis][download][branch] = "7.x"
projects[islandora_premis][download][revision] = "7e08d2c44e93666c47232986deb63f8719aba2a9"

projects[islandora_simple_workflow][type] = "module"
projects[islandora_simple_workflow][download][type] = "git"
projects[islandora_simple_workflow][download][url] = "https://github.com/Islandora/islandora_simple_workflow"
projects[islandora_simple_workflow][download][branch] = "7.x"
projects[islandora_simple_workflow][download][revision] = "3b0fe66044203fb77c181be75c604ebf742ef005"

projects[islandora_solr_search][type] = "module"
projects[islandora_solr_search][download][type] = "git"
projects[islandora_solr_search][download][url] = "https://github.com/Islandora/islandora_solr_search"
projects[islandora_solr_search][download][branch] = "7.x"
projects[islandora_solr_search][download][revision] = "ab38773d7f002126a2fafce6656535592294db45"

projects[islandora_solr_facet_pages][type] = "module"
projects[islandora_solr_facet_pages][download][type] = "git"
projects[islandora_solr_facet_pages][download][url] = "https://github.com/Islandora/islandora_solr_facet_pages"
projects[islandora_solr_facet_pages][download][branch] = "7.x"
projects[islandora_solr_facet_pages][download][revision] = "0c66ade58b12b3ada57307d8438894cf58ebf183"

projects[islandora_solr_metadata][type] = "module"
projects[islandora_solr_metadata][download][type] = "git"
projects[islandora_solr_metadata][download][url] = "https://github.com/Islandora/islandora_solr_metadata"
projects[islandora_solr_metadata][download][branch] = "7.x"
projects[islandora_solr_metadata][download][revision] = "e09da9e09b3b021636eaa8103cd2e1047e0f2e96"

projects[islandora_solr_views][type] = "module"
projects[islandora_solr_views][download][type] = "git"
projects[islandora_solr_views][download][url] = "https://github.com/Islandora/islandora_solr_views"
projects[islandora_solr_views][download][branch] = "7.x"
projects[islandora_solr_views][download][revision] = "acf1bf0d73bdd792a4561621c833eadd5d1414bc"

projects[islandora_xml_forms][type] = "module"
projects[islandora_xml_forms][download][type] = "git"
projects[islandora_xml_forms][download][url] = "https://github.com/Islandora/islandora_xml_forms"
projects[islandora_xml_forms][download][branch] = "7.x"
projects[islandora_xml_forms][download][revision] = "16400d44b77c41c25fa45c05026a0bca594e6deb"

projects[islandora_solution_pack_video][type] = "module"
projects[islandora_solution_pack_video][download][type] = "git"
projects[islandora_solution_pack_video][download][url] = "https://github.com/Islandora/islandora_solution_pack_video"
projects[islandora_solution_pack_video][download][branch] = "7.x"
projects[islandora_solution_pack_video][download][revision] = "2c7c9daefecaf998915a378437b5f29465dbac67"

projects[islandora_videojs][type] = "module"
projects[islandora_videojs][download][type] = "git"
projects[islandora_videojs][download][url] = "https://github.com/Islandora/islandora_videojs"
projects[islandora_videojs][download][branch] = "7.x"
projects[islandora_videojs][download][revision] = "8ba722979dd598cc2711863da18678d5d252ea95"

projects[islandora_solution_pack_web_archive][type] = "module"
projects[islandora_solution_pack_web_archive][download][type] = "git"
projects[islandora_solution_pack_web_archive][download][url] = "https://github.com/Islandora/islandora_solution_pack_web_archive"
projects[islandora_solution_pack_web_archive][download][branch] = "7.x"
projects[islandora_solution_pack_web_archive][download][revision] = "a5c7affe0b320fe8523272d9f25441596e4ca3b5"

projects[islandora_xacml_editor][type] = "module"
projects[islandora_xacml_editor][download][type] = "git"
projects[islandora_xacml_editor][download][url] = "https://github.com/Islandora/islandora_xacml_editor"
projects[islandora_xacml_editor][download][branch] = "7.x"
projects[islandora_xacml_editor][download][revision] = "10dabdd4159c4914ebf3371cc725b0f46cfa23f5"

projects[islandora_xmlsitemap][type] = "module"
projects[islandora_xmlsitemap][download][type] = "git"
projects[islandora_xmlsitemap][download][url] = "https://github.com/Islandora/islandora_xmlsitemap"
projects[islandora_xmlsitemap][download][branch] = "7.x"
projects[islandora_xmlsitemap][download][revision] = "1c706fa874ee23bb992df5674eb601668a44dda8"

projects[objective_forms][type] = "module"
projects[objective_forms][download][type] = "git"
projects[objective_forms][download][url] = "https://github.com/Islandora/objective_forms"
projects[objective_forms][download][branch] = "7.x"
projects[objective_forms][download][revision] = "684ce0f878f8cb98ad084c347c577b96e56ced7f"

projects[php_lib][type] = "module"
projects[php_lib][download][type] = "git"
projects[php_lib][download][url] = "https://github.com/Islandora/php_lib"
projects[php_lib][download][branch] = "7.x"
projects[php_lib][download][revision] = "bc7de5f39dbe574cc9d601107725feeb5a07c4af"

projects[subpathauto][type] = "module"
projects[subpathauto][download][type] = "git"
projects[subpathauto][download][url] = "https://github.com/OULibraries/subpathauto.git"
projects[subpathauto][download][branch] = "7.x-1.x-oulib"
projects[subpathauto][download][revision] = "f6eb3d001e32435b7679b63952382ec5fa31faf3"





; Libraries
defaults[libraries][download][overwrite] = TRUE

libraries[pdfjs][download][type] = "file"
libraries[pdfjs][download][url] = "https://github.com/mozilla/pdf.js/releases/download/v1.0.907/pdfjs-1.0.907-dist.zip"
libraries[pdfjs][directory_name] = "pdfjs"
libraries[pdfjs][type] = "library"

libraries[bookreader][download][type] = "file"
libraries[bookreader][download][url] = "https://github.com/Islandora/internet_archive_bookreader/archive/master.zip"
libraries[bookreader][directory_name] = "bookreader"
libraries[bookreader][type] = "library"

libraries[tuque][download][type] = "git"
libraries[tuque][download][branch] = "1.x"
libraries[tuque][download][url] = "http://github.com/Islandora/tuque.git"

libraries[colorbox][download][type] = "file"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/1.x.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[openseadragon][download][type] = "file"
libraries[openseadragon][download][url] = "http://openseadragon.github.io/releases/openseadragon-bin-0.9.129.zip"
libraries[openseadragon][directory_name] = "openseadragon"
libraries[openseadragon][type] = "library"

libraries[BagItPHP][download][type] = "git"
libraries[BagItPHP][download][url] = "git://github.com/scholarslab/BagItPHP.git"
libraries[BagItPHP][directory_name] = "BagItPHP"
libraries[BagItPHP][type] = "library"

libraries[video-js][download][type] = "file"
libraries[video-js][download][url] = "http://www.videojs.com/downloads/video-js-4.0.0.zip"
libraries[video-js][directory_name] = "video-js"
libraries[video-js][type] = "library"